### ISSUE TITLE
don't run game from GDEMU

### ISSUE THREAD

**Issue by megavolt85** [pcercuei/bloom#1]
https://github.com/pcercuei/bloom/blob/6e442279235d1b855a0b563d76de0a8ead76c5c0/src/cdr.c#L42
need add cdrom_reinit();

**Comment by pcercuei** [comment]
@megavolt85 I think I fixed it? Can you try it with the latest master?

**Comment by pcercuei** [comment]
Closing this issue as "assumed fixed".
