### ISSUE TITLE
pthread library  unavailable

### ISSUE THREAD

**Issue by ioamero** [pcercuei/bloom#2]
-- The C compiler identification is GNU 13.2.0
-- The CXX compiler identification is GNU 13.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /opt/dreamcast-sdk/utils/build_wrappers/kos-as
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/dreamcast-sdk/utils/build_wrappers/kos-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/dreamcast-sdk/utils/build_wrappers/kos-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Could NOT find Threads (missing: Threads_FOUND) 
CMake Error at deps/pcsx_rearmed/deps/lightrec/CMakeLists.txt:105 (message):
  Could not find compatible threads library

**Comment by pcercuei** [comment]
@ioamero your version of KallistiOS is likely too old.

**Comment by pcercuei** [comment]
Closing this issue as there's no feedback after a month, and it is a SDK issue and not an issue with Bloom itself.
